version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo "installing something"
    pre_build:
        commands: 
            - echo "This is the pre build phase"
    build:
        commands:
            - echo "This is the build phase"
            - echo "Here we can run some tests"
            - grep -Fq "Welcome" index.html  #this camand will fail in this branch as we edited html for failing
    post_build:
        commands:
            - echo "This is the post build phase"
            
artifacts:
  files:
    - '**/*'
  name: DevOpsAppArtifacts             
            
